### ISSUE TITLE
Settings -> Accessibility crashes the Settings app

### ISSUE THREAD

**Issue by sreinst1** [scotthartbti/android_frameworks_base#11]
When selecting Accessibility in the Settings, the Settings app crashes. Here's the logcat:

I/ActivityManager( 5599): Timeline: Activity_launch_request id:com.android.settings time:307354
I/ActivityManager( 2289): START u0 {act=android.intent.action.MAIN cmp=com.android.settings/.SubSettings (has extras)} from pid 5599
D/Yamaha-MC1N2-Audio( 1862): yamaha_mc1n2_audio_output_start()
D/Yamaha-MC1N2-Audio( 1862): yamaha_mc1n2_audio_route_start()
D/Yamaha-MC1N2-Audio( 1862): (yamaha_mc1n2_audio_params_route_find): device = 2, direction = 0
D/SubSettings( 5599): Launching fragment com.android.settings.accessibility.AccessibilitySettings
E/ActivityThread( 5599): Failed to inflate
E/ActivityThread( 5599): android.view.InflateException: Binary XML file line #69: Error inflating class com.android.settings.widget.SeekBarPreference
E/ActivityThread( 5599):    at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:441)
E/ActivityThread( 5599):    at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
E/ActivityThread( 5599):    at android.preference.GenericInflater.rInflate(GenericInflater.java:493)
E/ActivityThread( 5599):    at android.preference.GenericInflater.inflate(GenericInflater.java:326)
E/ActivityThread( 5599):    at android.preference.GenericInflater.inflate(GenericInflater.java:263)
E/ActivityThread( 5599):    at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272)
E/ActivityThread( 5599):    at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:285)
E/ActivityThread( 5599):    at com.android.settings.accessibility.AccessibilitySettings.onCreate(AccessibilitySettings.java:204)
E/ActivityThread( 5599):    at android.app.Fragment.performCreate(Fragment.java:1678)
E/ActivityThread( 5599):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:859)
E/ActivityThread( 5599):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
E/ActivityThread( 5599):    at android.app.BackStackRecord.run(BackStackRecord.java:684)
E/ActivityThread( 5599):    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
E/ActivityThread( 5599):    at android.app.Activity.performStart(Activity.java:5328)
E/ActivityThread( 5599):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2190)
E/ActivityThread( 5599):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2277)
E/ActivityThread( 5599):    at android.app.ActivityThread.access$800(ActivityThread.java:145)
E/ActivityThread( 5599):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
E/ActivityThread( 5599):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/ActivityThread( 5599):    at android.os.Looper.loop(Looper.java:136)
E/ActivityThread( 5599):    at android.app.ActivityThread.main(ActivityThread.java:5088)
E/ActivityThread( 5599):    at java.lang.reflect.Method.invokeNative(Native Method)
E/ActivityThread( 5599):    at java.lang.reflect.Method.invoke(Method.java:515)
E/ActivityThread( 5599):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/ActivityThread( 5599):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/ActivityThread( 5599):    at dalvik.system.NativeStart.main(Native Method)
E/ActivityThread( 5599): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.settings.widget.SeekBarPreference" on path: DexPathList[[zip file "/system/framework/org.cyanogenmod.hardware.jar", zip file "/system/priv-app/Settings.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/ActivityThread( 5599):    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/ActivityThread( 5599):    at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/ActivityThread( 5599):    at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/ActivityThread( 5599):    at android.preference.GenericInflater.createItem(GenericInflater.java:375)
E/ActivityThread( 5599):    at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:430)
E/ActivityThread( 5599):    ... 25 more
W/ContextImpl( 5599): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1154 android.app.ActivityThread.performLaunchActivity:2225 android.app.ActivityThread.handleLaunchActivity:2277 android.app.ActivityThread.access$800:145 android.app.ActivityThread$H.handleMessage:1206 
D/AndroidRuntime( 5599): Shutting down VM
W/dalvikvm( 5599): threadid=1: thread exiting with uncaught exception (group=0x41b38c80)
E/AndroidRuntime( 5599): FATAL EXCEPTION: main
E/AndroidRuntime( 5599): Process: com.android.settings, PID: 5599
E/AndroidRuntime( 5599): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: android.view.InflateException: Binary XML file line #69: Error inflating class com.android.settings.widget.SeekBarPreference
E/AndroidRuntime( 5599):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2227)
E/AndroidRuntime( 5599):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2277)
E/AndroidRuntime( 5599):    at android.app.ActivityThread.access$800(ActivityThread.java:145)
E/AndroidRuntime( 5599):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
E/AndroidRuntime( 5599):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5599):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 5599):    at android.app.ActivityThread.main(ActivityThread.java:5088)
E/AndroidRuntime( 5599):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5599):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 5599):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/AndroidRuntime( 5599):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 5599):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 5599): Caused by: android.view.InflateException: Binary XML file line #69: Error inflating class com.android.settings.widget.SeekBarPreference
E/AndroidRuntime( 5599):    at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:441)
E/AndroidRuntime( 5599):    at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
E/AndroidRuntime( 5599):    at android.preference.GenericInflater.rInflate(GenericInflater.java:493)
E/AndroidRuntime( 5599):    at android.preference.GenericInflater.inflate(GenericInflater.java:326)
E/AndroidRuntime( 5599):    at android.preference.GenericInflater.inflate(GenericInflater.java:263)
E/AndroidRuntime( 5599):    at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272)
E/AndroidRuntime( 5599):    at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:285)
E/AndroidRuntime( 5599):    at com.android.settings.accessibility.AccessibilitySettings.onCreate(AccessibilitySettings.java:204)
E/AndroidRuntime( 5599):    at android.app.Fragment.performCreate(Fragment.java:1678)
E/AndroidRuntime( 5599):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:859)
E/AndroidRuntime( 5599):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
E/AndroidRuntime( 5599):    at android.app.BackStackRecord.run(BackStackRecord.java:684)
E/AndroidRuntime( 5599):    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
E/AndroidRuntime( 5599):    at android.app.Activity.performStart(Activity.java:5328)
E/AndroidRuntime( 5599):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2190)
E/AndroidRuntime( 5599):    ... 11 more
E/AndroidRuntime( 5599): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.settings.widget.SeekBarPreference" on path: DexPathList[[zip file "/system/framework/org.cyanogenmod.hardware.jar", zip file "/system/priv-app/Settings.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime( 5599):    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 5599):    at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime( 5599):    at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime( 5599):    at android.preference.GenericInflater.createItem(GenericInflater.java:375)
E/AndroidRuntime( 5599):    at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:430)
E/AndroidRuntime( 5599):    ... 25 more
W/ActivityManager( 2289):   Force finishing activity com.android.settings/.SubSettings
W/ActivityManager( 2289):   Force finishing activity com.android.settings/.Settings
W/ActivityManager( 2289): Activity pause timeout for ActivityRecord{426d9bd0 u0 com.android.settings/.SubSettings t3 f}
I/ActivityManager( 2603): Timeline: Activity_idle id: android.os.BinderProxy@41defd68 time:308479
I/ActivityManager( 2289): Killing 3887:com.google.android.calendar/u0a58 (adj 15): empty #17

**Comment by scotthartbti** [comment]
Hmm...  I already see what is causing it to crash.  I'll take care of it
shortly.

**Comment by scotthartbti** [comment]
This was an issue in the settings package.  Thanks for the change log to allow me to easily correct the issue.  It is fixed with commit 194ec1b274b7626a454607757a6fc6a28a24e3ee
