### ISSUE TITLE
LockScreenInterface does not compile...

### ISSUE THREAD

**Issue by sreinst1** [scotthartbti/android_frameworks_base#12]
The following code in LockScreenInterface.java used to be commented out, but a recent commit un-commented it, and now it won't compile (there's no 'generalCategory' in this class):

```
    if (!hasButtons()) {   generalCategory.removePreference(findPreference(KEY_LOCKSCREEN_BUTTONS));
    }
```

**Comment by scotthartbti** [comment]
Shit forgot to add the other part before I passed out last night.  I'll get
it in there shortly.  This is in settings, not frameworks base.

**Comment by sreinst1** [comment]
Yes, I just don't know how to open an issue in Settings, which repository
does it belong to? I saw I can only add issues per repository in github.

**Comment by scotthartbti** [comment]
This was resolved 2 days ago when reported.  forgot the particular commit, but resolved.   Thanks for the report.
