### ISSUE TITLE
change language not work in setting

### ISSUE THREAD

**Issue by ammarsj** [scotthartbti/android_frameworks_base#13]
when all users change phone language to any other than english not change ....from the first release of our i9100 phone.....hope you can fix it ......thank 

what about gesture anywhere feature do you like it to merge it to your great rom ....please with appbar features .........thanks

**Comment by scotthartbti** [comment]
Fixed with commit d80dc74108938dfade2cef84db8fad59aec6907a

Thanks.

**Comment by ammarsj** [comment]
thank you
