### ISSUE TITLE
Battery Graph

### ISSUE THREAD

**Issue by ghost** [scotthartbti/android_frameworks_base#16]
Hey Scott,

I think I encountered a minor, I guess graphical/visual, bug with the battery graph. In the "History details" screen it always shows the device always as 'awake' even when it is definitely not [tested on other ROM's with same settings]. As this "problem" is not effecting my battery performance or creates any other issue, it is not that important. Though, I wanted to let you know about this.

**Comment by scotthartbti** [comment]
PatMac, this has been an issue since day one as far as i can tell.  Im not sure if there is a fix out there or not, honestly... i havent done any looking into it as it seems very minor to me.  If you happen to find something to remedy the issue, by all means let me know and ill implement it.

**Comment by scotthartbti** [comment]
This was fixed with commit 2d38807eb15e4e657e278637cbe9110fb779ef6b

Credit: Meticulus
