### ISSUE TITLE
art was not work properly,and you can see these to fix it 

### ISSUE THREAD

**Issue by moonlightly** [scotthartbti/android_frameworks_base#22]
These days i have see one method to fix art,you can see this link:https://github.com/MoKee/android_art/commit/fd60fbed81623bb29440bb18c4711fa391078f90  fix as this which you have add to other packages.Very thanks

**Comment by scotthartbti** [comment]
interesting... ill give it a whirl.  Thanks.

**Comment by scotthartbti** [comment]
fixed art and added a few additional optimizations.  Thanks for pointing out this issue.
