### ISSUE TITLE
Java 'symbol' errors

### ISSUE THREAD

**Issue by wantowan2** [scotthartbti/android_frameworks_base#4]
Thought I may as well say something as it doesn't look like it will be addressed any time soon.
For most MSM devices
"Can't find symbol" errors right through Bluetooth and IBluetooth. BluetoothManagerService.java
"""...............................................
            ^
frameworks/base/services/java/com/android/server/BluetoothManagerService.java:1162: class, interface, or enum expected
        mState = BluetoothAdapter.STATE_OFF;
        ^
frameworks/base/services/java/com/android/server/BluetoothManagerService.java:1164: class, interface, or enum expected
        mEnable = false;
        ^
frameworks/base/services/java/com/android/server/BluetoothManagerService.java:1166: class, interface, or enum expected
        if (mErrorRecoveryRetryCounter++ < MAX_ERROR_RESTART_RETRIES) {
        ^
frameworks/base/services/java/com/android/server/BluetoothManagerService.java:1170: class, interface, or enum expected
            mHandler.sendMessageDelayed(restartMsg, ERROR_RESTART_TIME_MS);
            ^
frameworks/base/services/java/com/android/server/BluetoothManagerService.java:1171: class, interface, or enum expected
        } else {
        ^
Proguard: /home/wantowan2/bs4/out/target/common/obj/JAVA_LIBRARIES/webviewchromium_intermediates/proguard.classes.jar
ProGuard, version 4.4
Reading program jar [/home/wantowan2/bs4/out/target/common/obj/JAVA_LIBRARIES/webviewchromium_intermediates/classes.jar]
178 errors

**Comment by scotthartbti** [comment]
You need to do a repo sync and make clean.  All those things that its
looking for have been reverted.  I build on multiple msm devices and have
no issues.

**Comment by scotthartbti** [comment]
I would also like to follow up with this by saying that normal troubleshooting steps should include doing what i mentioned above before assuming there is a build issue.
