### ISSUE TITLE
'Back' key does not close notification window

### ISSUE THREAD

**Issue by sreinst1** [scotthartbti/android_frameworks_base#7]
Drag down from the status bar shows the notifications. 'Back' button should close the notifications window (and show the previous activity) but it doesn't.

**Comment by scotthartbti** [comment]
Not sure what your reporting?  I tried to recreate what i think your reporting, but have no issues.  I pull down notification window and hit the back key and it closes the notification window as it should.  Logcat?

**Comment by ammarsj** [comment]
yes same problem… back button not work when i pull the notification… maybe device problem

**Comment by sreinst1** [comment]
Logcat does not show anything when I click the Back button when the notifications are shown. However, I do get the haptic feedback when I press the button, so I know that the device actually got the click. The last message from logcat is from the time I pull down the notifications from the status bar:
V/PanelView( 2389): animationTick called with dtms=0; nothing to do (h=287.94724 v=1605.0021)

Absolutely nothing when pressing the Back button. I tried a few times.

**Comment by scotthartbti** [comment]
You know the device got the click?  SMH.  The haptic feedback and the actual device key action handling are two completely different things..  I need more information.  What device are you using?  Are these nav keys or capacitive keys you speak of?   A logcat will give me an idea of whats going on in general...  You need to be as detailed as possible with me if you want this resolved as i said its working absolutely fine on my end.

**Comment by sreinst1** [comment]
I'm on Samsung Galaxy S2, GT-I9100. I'm referring to the capacitive key (the one to the right of the fixed, non-capacitive "Home" button). I'm not using the nav keys (I think you mean the nav bar that can be enabled in the ROM, right?). Like I said, I wrote logcat, but logcat produces NO output at all when I click the back capacitive key when the notifications are on. I see lots of output from logcat until I drag down the notifications, and then all output stops - nothing more until I drag the notifications window back up to the status bar. Maybe kmsg will help?

**Comment by sreinst1** [comment]
Ok, I'll make it clearer, to make sure there are no mis-understandings:
1. I am using Galaxy S2, GT-I9100. The status bar is at the top of the screen, showing the clock, the battery status, the reception, GPS icon (when GPS is active), etc.
2. I touch the status bar with one finger and drag down my finger. This shows me the notifications window. Maybe 'window' is misleading, sounds more like a curtain because that window is gradually becoming visible, the bottom of the window following my dragged finger. If I raise my finger after dragging it for about half the screen, the curtain keeps pulling down until the notifications window fills the screen. If there are any notifications there, I can swype them out to the right or left, or touch them to open the respective app.
3. Now, the notification list fills the entire screen. I touch the Back button, which is _below_ the LCD. The phone vibrates a bit (haptic feedback) but nothing happens besides this.

Now: If I connect my phone to the PC and type "adb logcat" (before step (2) above), I see loads of output (most of which in the Android buffer and not from the time I connected the phone). Once it's done pouring its buffer, the rate of output from logcat becomes very slow - only once in a while. Then I drag down the status bar (step (2)). The 'logcat' command does not produce any more output at this stage. The last output was a one-liner that occurred when I dragged down the status bar. I press 'Back' - still nothing in the output. I let the phone stay in this state for a while - to see that it's not some bufferring that prevents 'logout' from outputing data. I then drag the notifications "curtain" back up towards the status bar. Only then, logcat continues to produce output.
That's about it. In all other ROMs I've tried, the 'Back' button dismisses the notifications curtain - just like it does for other activities in Android. In Beanstalk, the Back button works everywhere except for the notifications curtain.

**Comment by sreinst1** [comment]
And here's some logcat. I paste the logcat output starting just before dragging down from the status bar, and until I drag up back to it.

W/GAV2    (30533): Thread[Service Reconnect,5,main]: Service unavailable (code=1), using local store.
W/ActivityManager(24070): Unable to start service Intent { act=com.google.android.gms.analytics.service.START cmp=com.google.android.gms/.analytics.service.AnalyticsService (has extras) } U=0: not found
D/SizeAdaptiveLayout(24189): com.android.internal.widget.SizeAdaptiveLayout{419db6f0 V.E..... ......ID 0,0-480,108 #7f07007b app:id/adaptive}child view android.widget.FrameLayout{42094290 V.E..... ......ID 0,0-480,96 #10202da android:id/status_bar_latest_event_content} measured out of bounds at 95px clamped to 108px
D/SizeAdaptiveLayout(24189): com.android.internal.widget.SizeAdaptiveLayout{421a15c0 V.E..... ......I. 0,0-0,0 #7f07007b app:id/adaptive}child view android.widget.FrameLayout{41a2e450 G.E..... ......ID 0,0-0,0 #10202da android:id/status_bar_latest_event_content} measured out of bounds at 95px clamped to 108px
D/SizeAdaptiveLayout(24189): com.android.internal.widget.SizeAdaptiveLayout{41cd81e0 V.E..... ......I. 0,0-0,0 #7f07007b app:id/adaptive}child view android.widget.FrameLayout{41dac538 G.E..... ......ID 0,0-0,0 #10202da android:id/status_bar_latest_event_content} measured out of bounds at 95px clamped to 108px
D/SizeAdaptiveLayout(24189): com.android.internal.widget.SizeAdaptiveLayout{419db6f0 V.E..... ......ID 0,0-480,108 #7f07007b app:id/adaptive}child view android.widget.FrameLayout{42094290 V.E..... ......ID 0,0-480,96 #10202da android:id/status_bar_latest_event_content} measured out of bounds at 95px clamped to 108px
D/SizeAdaptiveLayout(24189): com.android.internal.widget.SizeAdaptiveLayout{421a15c0 V.E..... ......I. 0,0-0,0 #7f07007b app:id/adaptive}child view android.widget.FrameLayout{41a2e450 G.E..... ......ID 0,0-0,0 #10202da android:id/status_bar_latest_event_content} measured out of bounds at 95px clamped to 108px
D/SizeAdaptiveLayout(24189): com.android.internal.widget.SizeAdaptiveLayout{41cd81e0 V.E..... ......I. 0,0-0,0 #7f07007b app:id/adaptive}child view android.widget.FrameLayout{41dac538 G.E..... ......ID 0,0-0,0 #10202da android:id/status_bar_latest_event_content} measured out of bounds at 95px clamped to 108px
V/PanelView(24189): animationTick called with dtms=0; nothing to do (h=538.5 v=2178.7615)
V/PanelView(24189): animationTick called with dtms=-6; nothing to do (h=538.5 v=2178.7615)
D/ConnectivityService(24070): Sampling interval elapsed, updating statistics ..
D/ConnectivityService(24070): Done.
D/ConnectivityService(24070): Setting timer for 720seconds
V/PanelView(24189): animationTick called with dtms=0; nothing to do (h=580.38116 v=-2012.2563)
V/PanelView(24189): animationTick called with dtms=0; nothing to do (h=580.38116 v=-2012.2563)
W/InputMethodManagerService(24070): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@422a43d8 attribute=null, token = android.os.BinderProxy@41ae4080

**Comment by sreinst1** [comment]
Now I read that this is called the "Notification shade". This problem is not specific to Beanstalk ROM, it also happens with Omni and SaberSlim ROMs. So I guess it's a general CM 11.0 problem. Simply when the notification shade is shown, Back button does not do anything that is user-visible (except for the haptic feedback).

**Comment by scotthartbti** [comment]
https://github.com/SlimRoms/frameworks_base/commit/69863a3115550b7fe38a3b806d80d8b362c5a486

That should fix your issue.  I'll pull it shortly.

**Comment by rrgrrg** [comment]
well done scott !! :) ...sorry for inturrupting but can you restore the dark dialer as its much better IMO ?

**Comment by scotthartbti** [comment]
If you like the darker dialer, why not use the dark stalk feature?  That's
why its set to a lighter color so that you have the option right there to
change the color to dark.

**Comment by sreinst1** [comment]
Thanks Scott. I'll try that.

**Comment by scotthartbti** [comment]
Should be fixed with commit ffb46cc2a4e2805894199a5f83a33ae9ed40cc34

**Comment by rrgrrg** [comment]
i know but also the dark theme isnt my type but its ok thanks anyway :D .. also for the record when using the beanstalk init.d scripts or build.prop the superuser app says it has given the permittion to sometimes "themes,settings or another app ..anyway it does that and notification keeps on going and doesnt stop until i restart the device

**Comment by sreinst1** [comment]
I confirm it's fixed. Thanks Scott!

**Comment by sreinst1** [comment]
Hi Scott,
Don't know which is the appropriate place to ask this. Maybe I've asked
before... The non-intrusive incoming call dialog does not work for me. I
get a blank "incall card", with no indication of the caller and no
accept/reject buttons. Now I know it's not ROM specific (happened to me
with Omni and Slim as well), and it's also not device specific, as others
with Beanstalk on the same device have it working. Any idea what can cause
it? I wish I could send a screenshot, but you can image the "incoming call"
rectangle at the bottom, being all white (or light gray?) with nothing in
it except for the icon of the caller (which shows a blank character).
Shlomy
