### ISSUE TITLE
long press navring not work

### ISSUE THREAD

**Issue by ammarsj** [scotthartbti/android_frameworks_base#8]
hi scott. .the navring button long press not work we wait for fix… and if you can also make the navbar buttons 7 not only 5 as choice please.navbar not navring… thanks in advance for supper nice rom…

**Comment by scotthartbti** [comment]
This is working absolutely fine from my end.

**Comment by ammarsj** [comment]
strange… i see many users in nexus have the problem… any way thank you i will see from where the problem

**Comment by scotthartbti** [comment]
Ah now I see.  Sorry I thought u meant regular navbar long press.  I see now that its navring long press and can confirm it is an issue.  I'll take a look and see what I can find.

**Comment by ammarsj** [comment]
yah this what i mean… thanks we wait.… and maybe also doing navbar 7 buttons as choice navbar not navring this time my friend

**Comment by scotthartbti** [comment]
Still looking into this one...  Not seeing anything that i missed and nothing is sticking out to me..  Do you know if nav ring long press has ever worked in any of the previous versions?  Would be helpful if i knew that information as im not sure if this has always been broken or if something that was recently commited caused it to stop working.

**Comment by ammarsj** [comment]
sorry but from first i9100 release from sooti it was broken. … not try this nice rom for our device support maybe you have some time to us please… i think sooti start build to us in 21/12 first release to i9100 users… one more thing please can you merge the package installer that show version info for apks during manuall instaler

**Comment by ammarsj** [comment]
![ytymu9en](https://f.cloud.github.com/assets/5116148/1869596/5b396752-787c-11e3-8746-441bee0d5550.jpg)

like this. … i found this in pound rom for i9100 user 4.4.2 if you look for its please

**Comment by ammarsj** [comment]
what about gesture anywhere feature do you think to merge it also.. please .it sooo nice feature…

**Comment by ammarsj** [comment]
sorry if i wrote more but i try all roms but never seen like your  rom.…great rom. . thanks soo much

**Comment by crunchbank** [comment]
Does anybody use Navring any more? Might be worth excising it altogether?

**Comment by scotthartbti** [comment]
Navring long press fixed with this commit 832d4b43e6876e16db1baf8b025f3875eef9f226
