### ISSUE TITLE
moving files from internal sd card

### ISSUE THREAD

**Issue by ammarsj** [scotthartbti/android_frameworks_base#9]
hi my friends…. when i moving files ftom sd card to my external card 32mb during movment it stop only from internal to external..when moving from folder in sd to other folder in sd also no problem or same for external… it is found from the first release to us i9100 users…. i hope you understand what i mean…. thanks

**Comment by scotthartbti** [comment]
This isnt a build issue.  This is a device/kernel side issue.  You need to report it to your device maintainer, not me.  Please only open tickets for issues that are confirmed to true issues.

**Comment by sooti** [comment]
That would be me, sorry scott, I keep telling them that hardware issues they report to me. in any case I'll look into the issue, but i need a logcat

**Comment by ammarsj** [comment]
sorry. that problem solved by sooti now. .sorry not try to do logcat…
